workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Add these environment variables in Codemagic
        APP_STORE_CONNECT_ISSUER_ID: your_issuer_id
        APP_STORE_CONNECT_KEY_IDENTIFIER: your_key_id
        APP_STORE_CONNECT_PRIVATE_KEY: your_private_key
        CERTIFICATE_PRIVATE_KEY: your_cert_private_key
    
    scripts:
      - name: Set up provisioning profiles
        script: |
          # Download and install the provisioning profile
          # This should be a Distribution/Ad Hoc profile with Push Notifications enabled
          curl -H "Authorization: Bearer $APP_STORE_CONNECT_PRIVATE_KEY" \
               -o profile.mobileprovision \
               "https://api.appstoreconnect.apple.com/v1/profiles/{profile_id}"
          
          # Install the profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      
      - name: Set up code signing certificate
        script: |
          # Install the distribution certificate
          echo $CERTIFICATE_PRIVATE_KEY | base64 --decode > /tmp/certificate.p12
          security create-keychain -p temp_password temp.keychain
          security import /tmp/certificate.p12 -k temp.keychain -P "" -T /usr/bin/codesign
          security list-keychains -s temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p temp_password temp.keychain
      
      - name: Flutter build
        script: |
          flutter packages get
          find . -name "Podfile" -execdir pod install \;
          
          # Build with explicit code signing
          flutter build ios --release \
            --export-options-plist=ios/ExportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa