// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUx6kTj34uo7vqcVml0NA4s4_miTTcR0',
    appId: '1:723311357828:web:d55617cf5b0a5282ab37d1',
    messagingSenderId: '723311357828',
    projectId: 'aimanagerfirebasebackend',
    authDomain: 'aimanagerfirebasebackend.firebaseapp.com',
    storageBucket: 'aimanagerfirebasebackend.firebasestorage.app',
    measurementId: 'G-GF71C63N9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4azQa88b6eeN1KKxnOckC2W_dmzUWWbg',
    appId: '1:723311357828:android:9b8387af3a3467b0ab37d1',
    messagingSenderId: '723311357828',
    projectId: 'aimanagerfirebasebackend',
    storageBucket: 'aimanagerfirebasebackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQS43ksT-EIT-4n-vdbHvj9VopCR8SdU',
    appId: '1:723311357828:ios:4d811ce89494623bab37d1',
    messagingSenderId: '723311357828',
    projectId: 'aimanagerfirebasebackend',
    storageBucket: 'aimanagerfirebasebackend.firebasestorage.app',
    iosBundleId: 'com.synoptic.AiDeviceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQS43ksT-EIT-4n-vdbHvj9VopCR8SdU',
    appId: '1:723311357828:ios:4d811ce89494623bab37d1',
    messagingSenderId: '723311357828',
    projectId: 'aimanagerfirebasebackend',
    storageBucket: 'aimanagerfirebasebackend.firebasestorage.app',
    iosBundleId: 'com.synoptic.AiDeviceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUx6kTj34uo7vqcVml0NA4s4_miTTcR0',
    appId: '1:723311357828:web:d59d7fd3265cc8cbab37d1',
    messagingSenderId: '723311357828',
    projectId: 'aimanagerfirebasebackend',
    authDomain: 'aimanagerfirebasebackend.firebaseapp.com',
    storageBucket: 'aimanagerfirebasebackend.firebasestorage.app',
    measurementId: 'G-GYSGT395X8',
  );
}
