# Include Flutter’s CocoaPods helper
install! 'cocoapods', :deterministic_uuids => false
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), 'flutter')

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # Firebase dependencies for cloud_firestore
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end